BillsHouse_MapScripts::
	.byte 0


CaramelTown_BillsHouse_Bill::
	msgbox CaramelTown_BillsHouse_Bill_Text_0, MSGBOX_NPC
	msgbox CaramelTown_BillsHouse_Bill_Text_1, MSGBOX_NPC
	msgbox CaramelTown_BillsHouse_Bill_Text_2, MSGBOX_NPC
	return


CaramelTown_BillsHouse_Bill_Text_0:
	.string "My daughter is the Gym leader in\n"
	.string "Gumdrop City$"

CaramelTown_BillsHouse_Bill_Text_1:
	.string "She took a trip to Hoenn last year and\n"
	.string "got so many powerful pokemon.$"

CaramelTown_BillsHouse_Bill_Text_2:
	.string "I'm so proud of her.$"
